### ISSUE TITLE
希望有下载QQ音乐和网易云音乐歌词保存csv的功能

### ISSUE THREAD

**Issue by benbenlang** [jitwxs/163MusicLyrics#101]
比如这个歌手https://y.qq.com/n/ryqq/singer/000FzZ3q3kxTMG
希望能下载保存全部歌词到csv 这样以后歌曲被和谐了歌词还能找到

**Comment by benbenlang** [comment]
最好把能看到的那些字段全部保存下来，比如歌曲名，图片地址，专辑名，歌手名，歌曲ID等，方便搜索

**Comment by jitwxs** [comment]
此需求非本需求目标功能，感谢提问。
