### ISSUE TITLE
日语罗马音和中文翻译有冲突

### ISSUE THREAD

**Issue by Lkhsss** [jitwxs/163MusicLyrics#102]
**BUG 描述 Describe the bug**
日语罗马音和中文翻译有冲突
~请在此处简要描述问题。A clear and concise description of what the bug is.~
如果开启了罗马音，就没有中文翻译
**版本 Version**
4.4
~告知您的版本。Tell us version.~
4.4
**复现步骤 Reclaim step**
1.开启罗马音设置
2.选择优先原文

**错误日志（可选） Error Log(Optional)**

~可上传程序 `Logs` 目录下的日志文件，帮助定位问题~

**Comment by jitwxs** [comment]
目前罗马音和译文只能二选一
