### ISSUE TITLE
Problem with Excluded Lyrics Lines for Translated Lyrics

### ISSUE THREAD

**Issue by daoxi** [jitwxs/163MusicLyrics#106]
So, in version [v4.2](https://github.com/jitwxs/163MusicLyrics/releases/tag/v4.2) and before, untranslated lyrics lines in translated lyrics were represented by `//`, for example:

> [01:23.45]//

but since [v4.3](https://github.com/jitwxs/163MusicLyrics/releases/tag/v4.3) dealt with [issue #85](https://github.com/jitwxs/163MusicLyrics/issues/85), now all untranslated lyrics lines are simply excluded/omitted. This creates a inconsistency (original lyrics and translated lyrics now have **different number of lines**) and makes it **much more difficult to identify untranslated lyrics lines** (e.g. to manually add translations)

To solve this problem, I think it'd be ideal to have 3 options for untranslated lyrics lines:

1. Exclude untranslated lyrics lines (which is the current behavior since [v4.3](https://github.com/jitwxs/163MusicLyrics/releases/tag/v4.3) dealt with [issue #85](https://github.com/jitwxs/163MusicLyrics/issues/85))
2. Represent untranslated lyrics lines with `//` (which is the old behavior in version [v4.2](https://github.com/jitwxs/163MusicLyrics/releases/tag/v4.2) and before)
3. Replace untranslated lyrics lines with their corresponding original lyrics lines' content (of the same timestamp). This is very useful because the translated lyrics won't miss any content even if some lyrics aren't translated. (most untranslated lyrics lines are English lyrics in a Japanese/Korean song, so it's still readable for Chinese users who can read English.).

For example, [this song](https://y.qq.com/n/ryqq/songDetail/000UjWxp0xgBWS) should produce the following results for the untranslated lyrics line (at `[00:47.85]`) in the translated lyrics, when each option is selected respectively:
Option 1:
(nothing, because it's excluded)
Option 2:

> [00:47.85]//

Option 3:

> [00:47.85]I wanna know
  

Hope that makes sense, it would be greatly appreciated if you could consider making this change.

**Comment by jitwxs** [comment]
thanks for your suggestion, i will resolve it in next version, options 1 and 3 will maybe provided.

**Comment by daoxi** [comment]
> thanks for your suggestion, i will resolve it in next version, options 1 and 3 will maybe provided.

Thank you so much, option 1 is already how the program currently behaves, so only option 3 needs to be implemented.

**Comment by jitwxs** [comment]
[v4.6](https://github.com/jitwxs/163MusicLyrics/releases/tag/v4.6) already support, see also [译文缺省规则](https://github.com/jitwxs/163MusicLyrics/wiki/4.x-Guide#423-%E8%AF%91%E6%96%87%E7%BC%BA%E7%9C%81%E8%A7%84%E5%88%99)
