### ISSUE TITLE
Untranslated Original Lyrics Lines not Showing in Translated Lyrics in Certain Lyrics Modes

### ISSUE THREAD

**Issue by daoxi** [jitwxs/163MusicLyrics#108]
First of all, thanks a lot for adding the new feature for [issue #106](https://github.com/jitwxs/163MusicLyrics/issues/106), but unfortunately it doesn't work properly for certain lyrics modes, take [that previously mentioned song](https://y.qq.com/n/ryqq/songDetail/000UjWxp0xgBWS) for example, when "填充原文" is selected:

It works fine with "优先原/译文（交错）" lyrics mode, but when "**仅显示译文**" lyrics mode is selected, the untranslated original lyrics **don't show/fill up** in the translated lyrics (**so it's still missing lyrics content**).

I personally only uses "仅显示原/译文" lyrics mode, but I also tested the other lyrics modes' behavior with "填充原文", such as "优先原/译文（独立）" and "优先原/译文（合并）" and found they also don't work as intended (try [that previously mentioned song](https://y.qq.com/n/ryqq/songDetail/000UjWxp0xgBWS) for example, and you will see what's wrong).

Version tested: [v4.6](https://github.com/jitwxs/163MusicLyrics/releases/tag/v4.6)

**Comment by jitwxs** [comment]
thank you for your feedback, this feature's implements indeed exist something bugs, i will fix it.
