### ISSUE TITLE
建议修改报错提示

### ISSUE THREAD

**Issue by unbelieverkevin** [jitwxs/163MusicLyrics#11]
例如
> ID: 411356061, Reason: 未将对象引用设置到对象的实例。

麻烦说“人话”，改成“歌词为空”之类的好吗 =ω=

**Comment by jitwxs** [comment]
感谢您的建议，已处理

**Comment by molkes** [comment]
@jitwxs 

v2.9版的窗口标题仍然是“网易云歌词提取 V2.8”，麻烦改一下。

**Comment by unbadfish** [comment]
这边建议你new一个issue呢，亲~
建议新建一个issue，每个issue里不要讨论其他话题~



---原始邮件---
发件人: "molkes"<notifications@github.com&gt;
发送时间: 2020年4月26日(周日) 晚上9:46
收件人: "jitwxs/163MusicLyrics"<163MusicLyrics@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"unbadfish"<3066893506@qq.com&gt;;
主题: Re: [jitwxs/163MusicLyrics] 建议修改报错提示 (#11)




 
@jitwxs
 
v2.9版的窗口标题仍然是“网易云歌词提取 V2.8”，麻烦改一下。
