### ISSUE TITLE
不会使用扫盘功能

### ISSUE THREAD

**Issue by 1514680963** [jitwxs/163MusicLyrics#110]
看文档没看懂扫盘功能怎么用

**Comment by jitwxs** [comment]
更新了下文档，加了动图 [3.1.3 扫盘搜索](https://github.com/jitwxs/163MusicLyrics/wiki/4.x-Guide#313-%E6%89%AB%E7%9B%98%E6%90%9C%E7%B4%A2)

**Comment by 1514680963** [comment]
原来扫盘是这个意思啊。我还以为是能扫出盘里的歌曲呢。。。
