### ISSUE TITLE
Extra/Duplicate Original Lyric Lines in Translated Lyrics

### ISSUE THREAD

**Issue by daoxi** [jitwxs/163MusicLyrics#115]
So, as of now there are [3 options to deal with untranslated lyric lines](https://github.com/jitwxs/163MusicLyrics/wiki/4.x-Guide#423-%E8%AF%91%E6%96%87%E7%BC%BA%E7%9C%81%E8%A7%84%E5%88%99), when I choose the last option (i.e. "填充原文") and the "仅显示译文" lyrics mode, something strange happens:

For [this song](https://y.qq.com/n/ryqq/songDetail/000zhc0u0JlLFm) for example, there are 3 extra/duplicate original lyric lines in translated lyrics, at `[01:12.78]`, `[01:19.02]`, and `[03:18.90]` respectively, in these 3 timestamps the translated lyric already exists (although the time is off by 0.01 second (`[00:00.01]`) for unknown reason) and thus the original lyric shouldn't be used to fill in these 3 timestamps.

This issue also seems to happen in other lyrics mode too. Another test example would be [this song](https://y.qq.com/n/ryqq/songDetail/002Nhmce4FhjuM), in which there're more extra/duplicate original lyric lines in translated lyrics. 

Version tested: [v4.8](https://github.com/jitwxs/163MusicLyrics/releases/tag/v4.8)

**Comment by jitwxs** [comment]
The reason for the difference in lyric timestamp between the origin and the translated  is that the server source file is not match, that's what you're talking about `[00:00.01]`.

If the timestamp is difference, the program can't match the original and translation lyrics in pairs. This scenario not easy to deal it.

**Comment by daoxi** [comment]
> The reason for the difference in lyric timestamp between the origin and the translated is that the server source file is not match, that's what you're say about `[00:00.01]`.
> 
> If the timestamp is difference, the program can't match the original and translation lyrics in pairs. This scenario not easy to deal it.

I see, something is probably wrong on the server side of the lyrics sources (which is definitely the fault of QQ/NetEase Music).

Would it be possible to solve this issue by **trying to match the original and translated lyric timestamps within an user-defined tiny interval** (e.g. `[00:00.01]`, or `[00:00.02]`, or `[00:00.05]`, etc.)? That will make the original/translated lyrics matching more tolerant of inaccuracy.

For example, if the interval is `[00:00.02]`, then the original lyric at `[00:14.47]` will be matched with `[00:14.45]`/`[00:14.46]`/`[00:14.47]`/`[00:14.48]`/`[00:14.49]` translated lyric (there's typically only one match, because **the lyrics' timestamps are typically more than `[00:00.02]` apart**).

I understand this isn't a perfect solution, but I can't think of a better way to deal with this issue.

**Comment by jitwxs** [comment]
see use guide: https://github.com/jitwxs/163MusicLyrics/wiki/4.x-Guide#424-%E8%AF%91%E6%96%87%E5%8C%B9%E9%85%8D%E7%B2%BE%E5%BA%A6
