### ISSUE TITLE
能不能加个歌曲封面获取的功能？

### ISSUE THREAD

**Issue by By-Tian** [jitwxs/163MusicLyrics#116]
能不能加个歌曲封面获取的功能？

**Comment by jitwxs** [comment]
没找到获取封面的 API 接口，这个不属于主功能，优先级较低

**Comment by textGamex** [comment]
> 没找到获取封面的 API 接口，这个不属于主功能，优先级较低

https://github.com/GEEKiDoS/NeteaseMuiscApi 这个项目有, 在 Detail方法返回的数据中
