### ISSUE TITLE
Missing Timestamps Where the Lyric Content is Empty

### ISSUE THREAD

**Issue by daoxi** [jitwxs/163MusicLyrics#117]
I recently tried downloading lyrics in other ways (e.g. [browser script](https://greasyfork.org/en/scripts/33046-%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E7%9B%B4%E6%8E%A5%E4%B8%8B%E8%BD%BD)), and found the MusicLyricApp has been **omitting/excluding empty timestamps** (i.e. timestamps where the lyric content is empty.)

Take [this song](https://music.163.com/#/song?id=625750) as an example, there should be empty timestamps at `[00:46.24]`, `[02:24.67]`, and `[04:03.15]`, **but these 3 timestamps are all omitted** in the lyrics obtained from MusicLyricApp.

These empty timestamps are actually pretty useful:
1. They tell the users when the lyric from the previous/last timestamp should end (and thus in the music player, the lyric is no longer highlighted once the vocal ends)
2. They divide the entire lyrics into smaller parts and thus improve organization, they also make the non-vocal parts visible in the lyrics.

Not every song has empty timestamps, but **they're quite useful when included (explained above)**. So perhaps consider stop omitting them? (Or better, offer a checkbox/togglable option to switch it on/off?)

Version tested: [v4.8](https://github.com/jitwxs/163MusicLyrics/releases/tag/v4.8)

**Comment by jitwxs** [comment]
Sounds reasonable, will offer a checkbox/togglable option to switch it on/off

**Comment by byf3332** [comment]
try use very old versions, I remember there was no such issue before

**Comment by daoxi** [comment]
> try use very old versions, I remember there was no such issue before

The older versions are missing some of the new features I need though.
