### ISSUE TITLE
一首歌里当不同歌手演唱被标注歌手名字时的歌词换行（\n）（合并符）的错误

### ISSUE THREAD

**Issue by kimycai** [jitwxs/163MusicLyrics#119]
![image](https://user-images.githubusercontent.com/17998728/188118477-d6dccd0f-1b5e-4625-8989-7ee8b6184a19.png)
虽然有换行，但把会“\n”换行符再次写入到歌词里，“\n”为自己填的合并符
比如图中的不同歌手：Ryan Gosling，Emma Stone
专辑id：001ZQRBO2251uY

**Comment by jitwxs** [comment]
这首歌看了QQ音乐数据源就是这样，不是程序给换行的。https://y.qq.com/n/ryqq/songDetail/004HRSPj2Z6jzA
![20220904162711852](https://user-images.githubusercontent.com/22422341/188304643-4a779dcb-1634-49d5-9270-427ce8d38edd.png)

**Comment by kimycai** [comment]
谢谢你的回复
