### ISSUE TITLE
Improving the resolution of retrieved cover artwork

### ISSUE THREAD

**Issue by daoxi** [jitwxs/163MusicLyrics#123]
So, [v4.9](https://github.com/jitwxs/163MusicLyrics/releases/tag/v4.9) now allows [getting the URL for cover artwork](https://github.com/jitwxs/163MusicLyrics/issues/116), which is pretty cool.

The resolution of retrieved cover artwork on QQ Music can be improved by simply tweaking the URL, for example:
`https://y.qq.com/music/photo_new/T002R300x300M0000045vTfy0d7CQR_1.jpg`
can be changed into:
`https://y.qq.com/music/photo_new/T002R800x800M0000045vTfy0d7CQR_1.jpg`
(note how the `300x300` part got changed to `800x800`, which seems to be the maximum that QQ Music allows)

If the cover artwork stored on the QQ Music server is less than `800x800`, it seems to be able to **automatically use the maximum resolution available**, for example:
`https://y.qq.com/music/photo_new/T002R800x800M000003VaRGL1OVb8W_1.jpg`
will fetch a jpg file at `500x500` (instead of `800x800`) because that's the maximum resolution available. In other words, **we can safely always use `800x800` in the URL, regardless of what's actually available from the QQ Music server**.

**Comment by jitwxs** [comment]
got it, thanks a lot
