### ISSUE TITLE
apple music有分辨率更高的封面可以下载

### ISSUE THREAD

**Issue by kimycai** [jitwxs/163MusicLyrics#124]
比如阿杜的专辑《天黑》，链接地址：https://music.apple.com/cn/album/%E5%A4%A9%E9%BB%91/1071022479

用F12查看可以找到图片地址为：
https://is4-ssl.mzstatic.com/image/thumb/Music125/v4/98/2c/1d/982c1dc2-54ed-89af-046a-0bb49853fcea/fengmian.jpg/1000x1000bb-60.jpg
其最后的1000x1000bb-60.jpg可以输出不同分辨率的图片，比如自己设置为3000x3000bb-60.jpg，实际不定是3000x3000，但是比QQ的封面要大多了，但是我找不到原始图片的地址，以后有需要可以考虑加入到程序内获取

**Comment by daoxi** [comment]
其实不用通过F12查看那么麻烦，直接在专辑图片上右键后点在新标签中打开图片即可看到网址，我之前专门写过一个[小工具用来把浏览器上获得的Apple Music专辑图片地址转换为其原图地址](https://github.com/daoxi/itunes-image-link-converter)（粘贴源码到收藏夹即可）。

或者也可以使用[Apple Music Artwork Finder](https://bendodson.com/projects/apple-music-artwork-finder/)(稍微麻烦些)，[之前我提示了作者后现在已可以直接获取原图了](https://github.com/bendodson/itunes-artwork-finder/issues/9)。

**Comment by daoxi** [comment]
其实不用通过F12查看那么麻烦，直接在专辑图片上右键后点在新标签中打开图片即可看到网址，我之前专门写过一个[小工具用来把浏览器上打开的Apple Music专辑图片标签页转换为其原图地址](https://github.com/daoxi/itunes-image-link-converter)（粘贴源码到收藏夹即可，觉得好用可以留个星）。

或者也可以使用[Apple Music Artwork Finder](https://bendodson.com/projects/apple-music-artwork-finder/)(稍微麻烦些)，[之前我提示了作者后现在已可以直接获取原图了](https://github.com/bendodson/itunes-artwork-finder/issues/9)。

Apple Music确实封面的分辨率通常更高（尤其是近年来发布的歌曲，[分辨率已是4000x4000起步](https://artists.apple.com/support/1120-cover-art)），不过曲库缺少一些小众的歌曲，可能是因为曲库里的基本都是发行商直接官方发布的歌曲吧。

**Comment by kimycai** [comment]
> 

原来如此，受教，感谢

**Comment by kimycai** [comment]
> 其实不用通过F12查看那么麻烦，直接在专辑图片上右键后点在新标签中打开图片即可看到网址，我之前专门写过一个[小工具用来把浏览器上打开的Apple Music专辑图片标签页转换为其原图地址](https://github.com/daoxi/itunes-image-link-converter)（粘贴源码到收藏夹即可，觉得好用可以留个星）。
> 
> 或者也可以使用[Apple Music Artwork Finder](https://bendodson.com/projects/apple-music-artwork-finder/)(稍微麻烦些)，[之前我提示了作者后现在已可以直接获取原图了](https://github.com/bendodson/itunes-artwork-finder/issues/9)。
> 
> Apple Music确实封面的分辨率通常更高（尤其是近年来发布的歌曲，[分辨率已是4000x4000起步](https://artists.apple.com/support/1120-cover-art)），不过曲库缺少一些小众的歌曲，可能是因为曲库里的基本都是发行商直接官方发布的歌曲吧。

有点看不懂用法，不过先给星lol
可以把用法写成中文吗

**Comment by daoxi** [comment]
浏览器(比如Chrome)中新建一个书签(也叫收藏夹)，书签名随意取，将[此链接](https://github.com/daoxi/itunes-image-link-converter/blob/master/scripts/script.bookmarklet.js)中的源码拷贝到该书签中填网址的那一栏，这样就设置完毕了。
进入图片地址(比如你[原提问中的这个](https://is4-ssl.mzstatic.com/image/thumb/Music125/v4/98/2c/1d/982c1dc2-54ed-89af-046a-0bb49853fcea/fengmian.jpg/1000x1000bb-60.jpg))，点击你刚才设置好的书签就会自动转换到原图地址了。

**Comment by kimycai** [comment]
> 
原来是script.bookmarklet.js源码链接找错了，怪不得访问不了

**Comment by byddgithubzh** [comment]
> 浏览器(比如Chrome)中新建一个书签(也叫收藏夹)，书签名随意取，将[此链接](https://github.com/daoxi/itunes-image-link-converter/blob/master/scripts/script.bookmarklet.js)中的源码拷贝到该书签中填网址的那一栏，这样就设置完毕了。 进入图片地址(比如你[原提问中的这个](https://is4-ssl.mzstatic.com/image/thumb/Music125/v4/98/2c/1d/982c1dc2-54ed-89af-046a-0bb49853fcea/fengmian.jpg/1000x1000bb-60.jpg))，点击你刚才设置好的书签就会自动转换到原图地址了。

你好，我有个问题，链接最开始的a1~5，这个1~5是随机的吗？

**Comment by daoxi** [comment]
> 你好，我有个问题，链接最开始的a1到a5，这个1到5是随机的吗？
> 实际测试下来，用1~5获取得到的原始图片似乎没什么区别。

a1到a5 是根据转换前的链接里的 is1-ssl到is5-ssl 进行自动对应的，比如is3-ssl转换后就是a3。
而is1-ssl到is5-ssl是苹果服务器分配的，目前is1-ssl到is5-ssl的规律未知（可能苹果那边也是随机的，用来分担单个服务器的压力）。

**Comment by byddgithubzh** [comment]
> 

js脚本可能需要修一修了，或者说是增加一个功能。
一张专辑的封面：[压缩后的图片](https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/81/0f/63/810f63df-9d75-0f49-81e0-5221ed11c83a/302910022.jpg/592x592bb.webp)https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/81/0f/63/810f63df-9d75-0f49-81e0-5221ed11c83a/302910022.jpg/592x592bb.webp
上面这个图片可以正常访问，使用您的js脚本获取原图链接为：[原始图片](https://a1.mzstatic.com/us/r1000/0/Music112/v4/81/0f/63/810f63df-9d75-0f49-81e0-5221ed11c83a/302910022.jpg)https://a1.mzstatic.com/us/r1000/0/Music112/v4/81/0f/63/810f63df-9d75-0f49-81e0-5221ed11c83a/302910022.jpg

但是获取到的原始图片链接并不能访问，然而把url开头位置的a1改为2~5的任意一个，却可以访问。所以，能不能给js脚本增加一个1~5随机的功能，可以让对应的数字出现的概率大一些。

**Comment by daoxi** [comment]
> > 
> 
> js脚本可能需要修一修了，或者说是增加一个功能。 一张专辑的封面：[压缩后的图片](https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/81/0f/63/810f63df-9d75-0f49-81e0-5221ed11c83a/302910022.jpg/592x592bb.webp) https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/81/0f/63/810f63df-9d75-0f49-81e0-5221ed11c83a/302910022.jpg/592x592bb.webp 上面这个图片可以正常访问，使用您的js脚本获取原图链接为：[原始图片](https://a1.mzstatic.com/us/r1000/0/Music112/v4/81/0f/63/810f63df-9d75-0f49-81e0-5221ed11c83a/302910022.jpg) https://a1.mzstatic.com/us/r1000/0/Music112/v4/81/0f/63/810f63df-9d75-0f49-81e0-5221ed11c83a/302910022.jpg
> 
> 但是获取到的原始图片链接并不能访问，然而把url开头位置的a1改为2~5的任意一个，却可以访问。所以，能不能给js脚本增加一个1或5随机的功能，可以让与原始对应的数字出现的概率大一些。

抱歉才看到，之前忙工作所以有段时间没上Github看了。

关于

> “但是获取到的原始图片链接并不能访问”

这可能是国内网络线路问题或苹果服务器暂时出了问题，因为我现在访问你提供的原图链接并未遇到任何问题。你如果在国内的话可以换个VPN线路试试。

关于

> “能不能给js脚本增加一个1或5随机的功能，可以让与原始对应的数字出现的概率大一些。”

实际上现在的脚本已经对应数字了，你压缩后图片链接里的数字是1（“is1-ssl”），原图链接里的数字（“a1”）也是1。

顺带一提，建议以后关于该脚本的提问或建议直接在[那个repo](https://github.com/daoxi/itunes-image-link-converter)下的[Issues](https://github.com/daoxi/itunes-image-link-converter/issues)里提，这样既方便我管理，也方便以后万一有其他用户能看到。

这个Issue感觉如果@jitwxs不打算添加新回复的话，可以关闭了。
