### ISSUE TITLE
建议添加对播放器高亮歌词的兼容更良好的分行翻译格式

### ISSUE THREAD

**Issue by bitvan** [jitwxs/163MusicLyrics#13]
以“优先原文”的双语歌词显示为例，目前该软件(以及不少其它软件)用的均是以下格式:
[00:00.03] 原文歌词1
[00:00.03] 原文翻译1
[00:00.07] 原文歌词2
[00:00.07] 原文翻译2
这个格式在用文本查看时一目了然，但有个很大的问题：对绝大多数播放器(如foobar2000的ESLyric插件，以前的千千静音，支持大量平台的Minilyrics等等)来说，其并不能正确的同时高亮两个时间轴相同的歌词，相应的，其会高亮两个时间轴相同的歌词中后面的那个。也就是说用户在观看该种格式的歌词时，会发现高亮的歌词永远是翻译。

所以我建议添加新的选项使在用户播放该格式歌词时高亮的是歌词原文而非歌词翻译，具体实现方法是：将歌词翻译置于歌词原文下一行的另一时间戳，该时间戳时间为下一句原文歌词的时间减去最小时间单位(0.01秒)
如: 
[00:01:30]原文1 
[00:01:79]翻译1 
[00:01:80]原文2
[00:02:29]翻译2
[00:02:30]原文3
[00:03:24]翻译3
......
这样的翻译格式虽然在用文本查看时会感觉时间轴很奇怪，但却可以保证在用任何播放器播放时永远都只高亮歌词原文(高亮翻译的0.01秒可忽略不计，在不打破LRC标准格式的情况下似乎没有其它方法)。

**Comment by jitwxs** [comment]
1. 相同的时间轴，如果你想要高亮的是原文的，选择 `优先译文` 即可（仅使用千千静听进行了测试）。
2. 如果你想同时显示，选择 `合并显示` 即可。

我觉得这两种，已经能够满足你提出的需求了。
