### ISSUE TITLE
歌词乱码

### ISSUE THREAD

**Issue by MercyzzCN** [jitwxs/163MusicLyrics#132]
不知是我的设备(MP3)编码错误还是什么

电脑上用UTF-8和unicode导出都没事 potplayer播放没乱码

一放到设备上就乱码 我也不知道为什么  但我每次把中文标点删掉或再复制到txt重新编辑完就没事了

**Comment by jitwxs** [comment]
请提供更多的复现步骤

**Comment by jitwxs** [comment]
试下 UTF-8-BOM 可以吗
