### ISSUE TITLE
下载某些逐字歌词报错

### ISSUE THREAD

**Issue by MC-dusk** [jitwxs/163MusicLyrics#135]
**BUG 描述 Describe the bug**

下载某些逐字歌词报错，其他逐字歌词则正常，暂时没看出报错和特定歌曲的联系。

**版本 Version**

5.2

**复现步骤 Reclaim step**

用例：https://y.qq.com/n/ryqq/songDetail/000sNzbP2nHGs2 
下载逐字歌词报错：`分析 EntityName 时出错。第18行，位置24。`
下载普通歌词正常。

> 还有个很迷的小问题：
https://y.qq.com/n/ryqq/songDetail/001RaE0n4RrGX9 
https://y.qq.com/n/ryqq/songDetail/204422870 
这两个链接指向同一首歌，但前者正常（逐字、普通歌词都有），后者获取不到歌词。

**Comment by jitwxs** [comment]
两个问题均已修复 [v5.3](https://github.com/jitwxs/163MusicLyrics/releases/tag/v5.3)
