### ISSUE TITLE
设置时间戳SSS为SS，逐字歌词仍为三位小数

### ISSUE THREAD

**Issue by MC-dusk** [jitwxs/163MusicLyrics#137]
**BUG 描述 Describe the bug**

设置时间戳毫秒`SSS`为两位小数（即厘秒`SS`），QQ音乐逐字歌词仍为三位小数（即毫秒）

**版本 Version**

5.3

**复现步骤 Reclaim step**

https://y.qq.com/n/ryqq/songDetail/000sNzbP2nHGs2
```
[01:40.22]傷[01:40.223]つ[01:40.541]く[01:40.829]こ[01:40.882]と[01:41.162] [01:41.450]喜[01:41.450]ぶ[01:42.166]こ[01:42.358]と[01:42.444]
```
（主要是有些播放器只支持两位小数，三位就不识别了）

**Comment by jitwxs** [comment]
[v5.4](https://github.com/jitwxs/163MusicLyrics/releases/tag/v5.4) 起已修复
