### ISSUE TITLE
[框架升级] 使用.NET 升级助手来升级项目框架

### ISSUE THREAD

**Issue by textGamex** [jitwxs/163MusicLyrics#142]
## 链接
[.NET 升级助手介绍](https://dotnet.microsoft.com/zh-cn/platform/upgrade-assistant/tutorial/intro)
[如何将winForm升级到.NET 6](https://learn.microsoft.com/zh-cn/dotnet/core/porting/upgrade-assistant-winforms-framework)

**Comment by jitwxs** [comment]
考虑到对普通用户的友好性，短期不会升级，dotnet7 应该 windows 没有预装
