### ISSUE TITLE
网易云自己歌单“我喜欢的音乐”的id输入，显示“歌单信息暂未被收入或查询失败”

### ISSUE THREAD

**Issue by LunarYuer** [jitwxs/163MusicLyrics#143]
希望能够支持“我喜欢的音乐”歌单

**Comment by jitwxs** [comment]
[v5.6](https://github.com/jitwxs/163MusicLyrics/releases/tag/v5.6) 已支持，需要提供 cookie 才可下载，详细见 [4.3 Cookie 设置](https://github.com/jitwxs/163MusicLyrics/wiki/4.x-Guide#43-cookie-%E8%AE%BE%E7%BD%AE)
