### ISSUE TITLE
关于QQ音乐链接精确提取

### ISSUE THREAD

**Issue by llq520** [jitwxs/163MusicLyrics#144]
**BUG 描述 Describe the bug**
提示您输入的id不合法

**版本 Version** 5.5

~告知您的版本。Tell us version.~

**复现步骤 Reclaim step**
我的操作是打开QQ音乐-选择一首歌播放-在窗口正下方歌曲名处点击鼠标右键
得到案例网址这个 https://c.y.qq.com/base/fcgi-bin/u?__=0S6Bg5scnbuj
点击精确查找提示您输入的id不合法

后改变策略 将 https://c.y.qq.com/base/fcgi-bin/u?__=0S6Bg5scnbuj网址粘贴到浏览器打开
得到如下网址https://y.qq.com/n/ryqq/songDetail/385359965?songtype=0 后点击精确查找获取成功
希望能优化ID提取策略。

**错误日志（可选） Error Log(Optional)**

~可上传程序 `Logs` 目录下的日志文件，帮助定位问题~
2022-12-15 15:38:41.3609 | ERROR | Search music lyric failed, param: "https://c.y.qq.com/base/fcgi-bin/u?__=0S6Bg5scnbuj", type: SONG_ID, message: "您输入的ID不合法"

PS：我已经制作了一个软件使用教程视频。
网址、
https://www.xiaohongshu.com/discovery/item/6399a6aa000000001f00987b
希望精确查找修复后我更新下一个教程视频。

**Comment by llq520** [comment]
另外希望增加模糊搜索结果表单数据字段来源平台

**Comment by jitwxs** [comment]
[v5.6](https://github.com/jitwxs/163MusicLyrics/releases/tag/v5.6) 已支持

**Comment by llq520** [comment]
给力，赞！
