### ISSUE TITLE
大佬你好. 請問可以新增英文翻譯嗎

### ISSUE THREAD

**Issue by gt2525** [jitwxs/163MusicLyrics#146]
如題
希望可以的話能同時展示

原文
羅馬音
英文

一開始翻譯不是很精確也沒關西 
感謝大老

**Comment by jitwxs** [comment]
[v5.7](https://github.com/jitwxs/163MusicLyrics/wiki/5.7-Plus-Guide#4512-%E7%BF%BB%E8%AF%91-api) 版本已支持
