### ISSUE TITLE
建议新增自动跳过纯音乐歌词下载的功能

### ISSUE THREAD

**Issue by szlysms** [jitwxs/163MusicLyrics#147]
一整个歌单下载时可能会有很多的歌曲歌词是“纯音乐，请欣赏”等等
如果大佬愿意的话，可以考虑一下加一个“不下载纯音乐歌词（或不保存）”的选项

**Comment by jitwxs** [comment]
[v5.7](https://github.com/jitwxs/163MusicLyrics/wiki/5.7-Plus-Guide#452-%E8%B7%B3%E8%BF%87%E7%BA%AF%E9%9F%B3%E4%B9%90) 版本已支持
