### ISSUE TITLE
大佬好，这里是关于文件名输出的一些小建议

### ISSUE THREAD

**Issue by will1074** [jitwxs/163MusicLyrics#148]
可不可增加一个按照专辑曲序输出文件名的功能呢？现在输出文件名的三种格式如果强迫症想要按曲序排号的话有点麻烦，如果可以按照曲序输出文件名例如说“01. 歌曲名.lrc”这样子的话就好了，如果还可以自定义输出文件名格式的话就更好啦，还可以根据喜好选择改成例如说“01 - 歌曲名”或者是“01 歌曲名”这样子，如果大佬可以考虑一下后续更新这个功能将感激不尽！

**Comment by jitwxs** [comment]
[v5.7](https://github.com/jitwxs/163MusicLyrics/wiki/5.7-Plus-Guide#453-%E8%BE%93%E5%87%BA%E6%96%87%E4%BB%B6%E5%90%8D) 版本已支持

**Comment by will1074** [comment]
大佬好！在收到您的回复后第一时间下载了最新版本体验，但是有些苦恼的是输出的序号1-9位数只能是单位的，有没有可能性在后续更新的时候让序号对齐到两位数是01-09这样子的呢？不论如何非常感谢大佬愿意采纳先前提出的建议！！！！



> [v5.7](https://github.com/jitwxs/163MusicLyrics/wiki/5.7-Plus-Guide#453-%E8%BE%93%E5%87%BA%E6%96%87%E4%BB%B6%E5%90%8D) 版本已支持

**Comment by jitwxs** [comment]
可以的，后续版本加入

**Comment by jitwxs** [comment]
[v5.8](https://github.com/jitwxs/163MusicLyrics/wiki/5.7-Plus-Guide#453-%E8%BE%93%E5%87%BA%E6%96%87%E4%BB%B6%E5%90%8D) 版本已支持
