### ISSUE TITLE
希望能提取LYRICAL NONSENSE的歌詞

### ISSUE THREAD

**Issue by gt2525** [jitwxs/163MusicLyrics#151]
https://www.lyrical-nonsense.com/global/

如題
希望可以提取更多不同網站的歌詞
謝謝大佬

**Comment by jitwxs** [comment]
用途是啥呢，看起来歌词没有时间戳的数据

**Comment by gt2525** [comment]
我是想新增不同網站提取歌詞的話應該資源會更完整
也許會有網易雲和QQ沒有的資源

**Comment by jitwxs** [comment]
主要是没有时间戳的数据，拿到了也用处不大
