### ISSUE TITLE
英文歌只能一起下英文和译文

### ISSUE THREAD

**Issue by IMDOOWU** [jitwxs/163MusicLyrics#157]
英文歌只能一起下英文和译文，可不可以分开？

**Comment by jitwxs** [comment]
请提供具体歌曲链接以便测试

**Comment by daoxi** [comment]
@jitwxs 我猜题主指的是输出歌词时可不可以分开成两个不同的文件（而非合并到同一个文件中），说实话这跟歌是什么语言的应该没关系。

我[提了类似的Issue](https://github.com/jitwxs/163MusicLyrics/issues/163)后才看到这个Issue，看来我不是唯一需要这功能的😏

**Comment by jitwxs** [comment]
#163
