### ISSUE TITLE
app 逻辑错误

### ISSUE THREAD

**Issue by llq520** [jitwxs/163MusicLyrics#161]
**BUG 描述 Describe the bug**

~请在此处简要描述问题。A clear and concise description of what the bug is.~
希望模糊搜索歌曲名能多平台搜索，而不是要选择了平台搜索对应平台

**版本 Version**  5.8

~告知您的版本。Tell us version.~

**复现步骤 Reclaim step**

~1. xxx 输入关键字
2. xxx 模糊搜索
3. xxx~ 默认是搜索网易云

**错误日志（可选） Error Log(Optional)**

~可上传程序 `Logs` 目录下的日志文件，帮助定位问题~

**Comment by jitwxs** [comment]
since [v5.9](https://github.com/jitwxs/163MusicLyrics/releases/tag/v5.9) support this feature, [click here](https://github.com/jitwxs/163MusicLyrics/wiki/5.7-Plus-Guide#445-%E8%81%9A%E5%90%88%E6%A8%A1%E7%B3%8A%E6%90%9C%E7%B4%A2) to read more.
