### ISSUE TITLE
Google Pinyin (Input Method) not Working in the Search Field

### ISSUE THREAD

**Issue by daoxi** [jitwxs/163MusicLyrics#162]
Version used: [v5.8](https://github.com/jitwxs/163MusicLyrics/releases/tag/v5.8)

Now we're able to search for a song's title or artist by entering the name in the search field (aka "模糊搜索" in the app), **but I can't seem to type anything other than English** (for unknown reason), looks like Google Pinyin (and probably other input methods too) got disabled when typing in the search field.

Could you kindly look into this issue?

**Comment by jitwxs** [comment]
Our application not restrictions input content, can you try copy-paste method, or other input tools.

I use Google Pinyin 2.7.25.128 version and win10, it works normal.

![EfUHL.gif](https://i.328888.xyz/2023/02/25/EfUHL.gif)

**Comment by daoxi** [comment]
Hmm...that's weird, I use the exact same version of Google Pinyin as you do, perhaps something went wrong from my end, I'll just copy and past then.

Thanks a lot for the feedback.

**Comment by daoxi** [comment]
Hmm...that's weird, I use the exact same version of Google Pinyin as you do, perhaps something went wrong from my end, I'll just copy and past then.

Thanks a lot for the feedback.

**Comment by daoxi** [comment]
Hmm...that's weird, I use the exact same version of Google Pinyin as you do, perhaps something went wrong from my end, I'll just copy and past then.

Thanks a lot for the feedback.
