### ISSUE TITLE
Export different versions of lyrics into separate files

### ISSUE THREAD

**Issue by daoxi** [jitwxs/163MusicLyrics#163]
So, I'm trying to export the original and translated lyrics into **separate files**:

It was easier to do in the past, but after the setting for selecting original/translated lyrics got moved to the settings panel, now if I want original/translated lyrics in their own seperate files, I'd have to manually go into the settings panel for each export.

The current option "独立" will concatenate both the original and translated lyrics into 1 single file. Would it be possible to instead have another option that **exports the original and translated lyrics into their own separate files**?

**Comment by jitwxs** [comment]
since [v5.9](https://github.com/jitwxs/163MusicLyrics/releases/tag/v5.9) support this feature, [click here](https://github.com/jitwxs/163MusicLyrics/wiki/5.7-Plus-Guide#454-%E7%8B%AC%E7%AB%8B%E6%AD%8C%E8%AF%8D%E6%A0%BC%E5%BC%8F%E5%88%86%E6%96%87%E4%BB%B6%E4%BF%9D%E5%AD%98) to read more.
