### ISSUE TITLE
希望读取监测剪贴板能灵活些

### ISSUE THREAD

**Issue by itianmi** [jitwxs/163MusicLyrics#165]
有时候，我准备自己输入内容到搜索框时(或需要修改、删减一部分复制内容时)，它老是覆盖我手打进去的。
所以希望有这两个机制：
1、窗口在前台的时候，再读取监测剪切板。
2、监测到输入操作的时候，自动暂停读取剪切板，3秒再重新读取监测。

**Comment by jitwxs** [comment]
[v6.0](https://github.com/jitwxs/163MusicLyrics/releases/tag/v6.0) 版本已优化问题，感谢反馈。
