### ISSUE TITLE
专辑获取直链希望能自动匹配歌曲名

### ISSUE THREAD

**Issue by llq520** [jitwxs/163MusicLyrics#168]
*描述您期望的功能 Describe your feature**

~请在此输入。Please input here.~
专辑获取直链希望能自动匹配歌曲名 如题 
案例：
https://music.163.com/album?id=124065116&userid=117315533
、
解析到的地址如下
id,songLink
1825885822,http://m701.music.126.net/20230319221229/aff5bedc78e20980d6cd02e0c250dfe9/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/7811727870/2222/0ac7/131a/9118f9f7aa1370e8b74797c30b21d55a.mp3
1825882199,http://m701.music.126.net/20230319221230/8fe0c9f6377e2b370c1271fb059d23eb/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/7811729012/5fac/c15b/6920/581958d9d3b9f5d1f6f1b863081ada41.mp3
1825885823,http://m801.music.126.net/20230319221230/9cf207ab8d13e44d20b65a84b6ccf2de/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/7811727657/faad/1668/ecdb/16e07b9d15d0e1e67cf7bd01c3d693d6.mp3
1825885824,http://m701.music.126.net/20230319221230/f6045fc03aed92b139adfb6762dcaa92/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/7811728224/3d9f/7f45/d5db/2607418a36ba3e3a5966444c241f7f17.mp3
1825882200,http://m801.music.126.net/20230319221230/193ec0eb48dfdbef5b56d1551be18df2/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/7811732223/94e3/d8b9/c9e4/85d528bf0a243f1488b41ad84a1b496b.mp3
1825882201,http://m801.music.126.net/20230319221230/4bb46aac466980fe3ac2443f5500e4bb/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/7811728307/7b09/9759/a2a8/156ca7cb2beceb40847481aa1f40fea6.mp3
1825885825,http://m801.music.126.net/20230319221230/c752f6c2e3edb85c1d55c9ac92839910/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/7811727601/262b/2ef9/2f8e/5d95d0bb7e079199f9354ff29f0582a8.mp3
1825882202,http://m701.music.126.net/20230319221230/302b048026467194dca839b8a94e911a/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/7811726836/35f7/689b/6607/7ed2ca6525447007c975f60373cfe9f9.mp3
1825885826,http://m801.music.126.net/20230319221230/7170798a049ed1e3e6ac2c2a1ffaa012/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/7811728417/c7fe/dba9/c096/ebc32355eb34d2a3ffa19dd8b9280a07.mp3
1825885827,http://m801.music.126.net/20230319221230/9b5bfa630fd0a33edba87fc4364dfb94/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/7811728599/7ada/4efd/c355/760371e6bd3fe34b28507429970970b1.mp3
1825882203,http://m801.music.126.net/20230319221231/5dc5c3dc99c63c6acc3c975ef5b7a942/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/7811728627/779d/1576/f4b7/9eb62b2c34a63dee2675f54c48ff079d.mp3
1825882204,http://m701.music.126.net/20230319221231/72d68b0d683b9a4fabcf86cd6df8a51a/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/7811729396/f0f7/1c6f/d79f/115432239ee48655a7b76c2627950f48.mp3
1825885828,http://m801.music.126.net/20230319221231/3605cbba2c7e75ebc41ac50bc3f4e6ae/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/7811731673/764e/9531/af72/41d5914ecd1844b64e216ba450593ce9.mp3

文件名编码如下

obj_wo3DlMOGwrbDjj7DisKw_7811726836_35f7_689b_6607_7ed2ca6525447007c975f60373cfe9f9.mp3
obj_wo3DlMOGwrbDjj7DisKw_7811727601_262b_2ef9_2f8e_5d95d0bb7e079199f9354ff29f0582a8.mp3
obj_wo3DlMOGwrbDjj7DisKw_7811727657_faad_1668_ecdb_16e07b9d15d0e1e67cf7bd01c3d693d6.mp3
obj_wo3DlMOGwrbDjj7DisKw_7811727870_2222_0ac7_131a_9118f9f7aa1370e8b74797c30b21d55a.mp3
obj_wo3DlMOGwrbDjj7DisKw_7811728224_3d9f_7f45_d5db_2607418a36ba3e3a5966444c241f7f17.mp3
obj_wo3DlMOGwrbDjj7DisKw_7811728307_7b09_9759_a2a8_156ca7cb2beceb40847481aa1f40fea6.mp3
obj_wo3DlMOGwrbDjj7DisKw_7811728417_c7fe_dba9_c096_ebc32355eb34d2a3ffa19dd8b9280a07.mp3
obj_wo3DlMOGwrbDjj7DisKw_7811728599_7ada_4efd_c355_760371e6bd3fe34b28507429970970b1.mp3
obj_wo3DlMOGwrbDjj7DisKw_7811728627_779d_1576_f4b7_9eb62b2c34a63dee2675f54c48ff079d.mp3
obj_wo3DlMOGwrbDjj7DisKw_7811729012_5fac_c15b_6920_581958d9d3b9f5d1f6f1b863081ada41.mp3
obj_wo3DlMOGwrbDjj7DisKw_7811729396_f0f7_1c6f_d79f_115432239ee48655a7b76c2627950f48.mp3
obj_wo3DlMOGwrbDjj7DisKw_7811731673_764e_9531_af72_41d5914ecd1844b64e216ba450593ce9.mp3
obj_wo3DlMOGwrbDjj7DisKw_7811732223_94e3_d8b9_c9e4_85d528bf0a243f1488b41ad84a1b496b.mp3

需要匹配文件名如下
1对你说晚安石进
2被辜负的青春石进
3男和女石进
4夏语石进
5无言的告别石进
6隐没的天使石进
7记得有人在等你石进
8她的悲伤石进
9致叶小安的信石进
10铁塔下的舞会石进

**Comment by jitwxs** [comment]
[v6.0](https://github.com/jitwxs/163MusicLyrics/releases/tag/v6.0) 版本已优化该体验，感谢反馈。
