### ISSUE TITLE
“强制两位”可否考虑一下做成四舍五入的形式？

### ISSUE THREAD

**Issue by hui-shao** [jitwxs/163MusicLyrics#17]
不得不说，软件很好用，一下子就解决了下载和格式化的问题。
一个小小的请求：
例如：
`[00:19.778]` 变为 `[00:19.78]`

**Comment by jitwxs** [comment]
我这边并没有需要“强制两位”功能的设备，请问要使用“四舍五入”而不是“截位”的原因是？

**Comment by hui-shao** [comment]
> 我这边并没有需要“强制两位”功能的设备，请问要使用“四舍五入”而不是“截位”的原因是？

嗯，我的mp3是只支持两位数的时间的（Sony-NW-A55），所以为了时间能尽量准确一点，个人是比较喜欢四舍五入一下的。
当然，具体是四舍五入还是直接截取，不算是特别重要的一个功能，感觉如果用四舍五入，算是一个小细节的优化吧。

**Comment by jitwxs** [comment]
了解，该功能会在下一版本中加入，请留意该 ISSUE 状态或版本更新。

**Comment by jitwxs** [comment]
#
