### ISSUE TITLE
批量保存失败，如图所示

### ISSUE THREAD

**Issue by kimycai** [jitwxs/163MusicLyrics#170]
**BUG 描述 Describe the bug**

~请在此处简要描述问题。A clear and concise description of what the bug is.~

**版本 Version**
5.9

~告知您的版本。Tell us version.~
windows版
**复现步骤 Reclaim step**

1. 搜 002JfIs20njEAb
2. 如图所示保存后弹出错误提示
https://github.com/kimycai/hello-github-actions/blob/daa5f79d96cb1af5f27a52aa1716d183c7731623/xxx.jpg
**错误日志（可选） Error Log(Optional)**

~可上传程序 `Logs` 目录下的日志文件，帮助定位问题~

**Comment by jitwxs** [comment]
可以粘贴下 `MusicLyricAppSetting.json` 配置信息，还有 `Logs` 目录下的错误日志吗，我尝试没有复现问题

**Comment by kimycai** [comment]
{"Config":{"RememberParam":false,"AggregatedBlurSearch":false,"AutoReadClipboard":false,"AutoCheckUpdate":true,"IgnorePureMusicInSave":true,"SeparateFileForIsolated":false,"OutputFileNameFormat":"${name} - ${singer}","OutputLyricTypes":"1,0","QQMusicCookie":"","NetEaseCookie":"","TransConfig":{"LostRule":0,"MatchPrecisionDeviation":700,"RomajiModeEnum":1,"RomajiSystemEnum":2,"BaiduTranslateAppId":"","BaiduTranslateSecret":"","CaiYunToken":""}},"Param":{"SearchSource":0,"SearchType":0,"ShowLrcType":0,"LrcMergeSeparator":"","LrcTimestampFormat":"[mm:ss.SSS]","SrtTimestampFormat":"HH:mm:ss,SSS","EnableVerbatimLyric":false,"IgnoreEmptyLyric":true,"DotType":0,"OutputFileFormat":0,"Encoding":0}}

**Comment by kimycai** [comment]
索引超出范围的错误结果是，歌词只能下载一半多曲目，剩余的曲目没有歌词文件生成

**Comment by kimycai** [comment]
我大概测试出来了，我把更多设置里的“译文匹配精度”调高了，比如设置为700ms，就会碰到此类错误，设置小一点不会，但是设置小了，如果是合并原文译文的，那么译文和原文不会同合并符连接在一起，反而是分行的

**Comment by kimycai** [comment]
另外，如果只有中文歌词（单一语种），歌词格式选择合并时也会出现错误提示，但选择独立模式就正常了

**Comment by kimycai** [comment]
如果将歌词格式选为”交错“，而非”合并“（合并时总是会出错），那么歌词基本能正常导出不会出错。

**Comment by jitwxs** [comment]
感谢排查，问题已定位，下一版本修复

**Comment by jitwxs** [comment]
[v6.0](https://github.com/jitwxs/163MusicLyrics/releases/tag/v6.0) 版本已修复该问题。
