### ISSUE TITLE
找不到设置按钮

### ISSUE THREAD

**Issue by Rizumu85** [jitwxs/163MusicLyrics#178]
**BUG 描述 Describe the bug**
我这边看不到设置按钮
![image](https://github.com/jitwxs/163MusicLyrics/assets/25150828/d18498fe-f76e-4cb1-b9d5-65400a2d823a)

**版本 Version**
6.0

**复现步骤 Reclaim step**
打开既有

**错误日志（可选） Error Log(Optional)**
![image](https://github.com/jitwxs/163MusicLyrics/assets/25150828/af8646e0-db18-4d64-9f28-52375d8e8deb)

**Comment by Rizumu85** [comment]
我使用强制Resize的软件ResizeEnableRunner后，设置露出来了
![image](https://github.com/jitwxs/163MusicLyrics/assets/25150828/da536861-4fb6-4036-b207-15cbf97b2895)

**Comment by jitwxs** [comment]
可以提供下信息： windows 版本，当前分辨率，缩放百分比。

**Comment by zhongerjunze** [comment]
> 可以提供下信息： windows 版本，当前分辨率，缩放百分比。

虽然不是该issue的发起人，但我也有同样的问题，并使用ResizeEnableRunner解决了这个问题。

相关信息：
版本	Windows 10 家庭中文版
版本号	22H2
操作系统内部版本	19045.4046
体验	Windows Feature Experience Pack 1000.19053.1000.0
分辨率：1920*1080
缩放：125%
在缩放更改为100%的情况下，仍无法正常显示设置

个人感觉是窗口在该情况下太小，导致无法完全显示

**Comment by Rizumu85** [comment]
Edition	Windows 11 Pro
Version	23H2
OS build	22631.3155
缩放：110
分辨率：2560×1440

**Comment by jitwxs** [comment]
https://github.com/jitwxs/163MusicLyrics/releases/tag/v6.5
