### ISSUE TITLE
中英文歌词顺序问题

### ISSUE THREAD

**Issue by suboyang** [jitwxs/163MusicLyrics#181]
**中英文歌词顺序问题**

~中英文歌词顺序问题，同一句歌词，英文和中文的歌词的时间戳不应该是一样的!

**版本  v6.0**

正常的中英文歌词是这样的。
00:27]Well I'll be damned
[00:30]噢，我真该死
[00:30]Here comes your ghost again
[00:34]你的幻影又再出现
[00:34]But that's not unusual

每一句中文歌词的时间戳改为其后一句英文歌词的时间戳！！！

这样中英文词才可以正常显示

**Comment by daoxi** [comment]
可以参考[这个Issue](https://github.com/jitwxs/163MusicLyrics/issues/171)内的讨论内容
