### ISSUE TITLE
批量保存失败，显示内存资源不足，无法处理此命令

### ISSUE THREAD

**Issue by GFF0019** [jitwxs/163MusicLyrics#187]
**BUG 描述 Describe the bug**
显示内存资源不足，无法处理此命令
~请在此处简要描述问题。A clear and concise description of what the bug is.~
批量保存失败，显示内存资源不足，无法处理此命令。试了两次，第一次保存到六十多首就显示失败然后停止了，第二次还没开始刚点保存就显示失败，也是说内存资源不足
**版本 Version**
v6.0
~告知您的版本。Tell us version.~

**复现步骤 Reclaim step**

~1. 导入歌单编码8385087613，选择“歌单”，点击“精确搜索”，等待全部搜索完毕
2. 进入“更多设置”，改变保存文件名为“${singer} - ${name}”，启用“原文，原始译文，罗马音译文”
3. [点击“保存”，选择文件夹，随后问题出现](url)

**错误日志（可选） Error Log(Optional)**

~可上传程序 `Logs` 目录下的日志文件，帮助定位问题~
[2023-11-04.log](https://github.com/jitwxs/163MusicLyrics/files/13255730/2023-11-04.log)

**Comment by jitwxs** [comment]
[v6.1](https://github.com/jitwxs/163MusicLyrics/releases/tag/v6.1) 版本已优化该功能，感谢反馈。
