### ISSUE TITLE
6.0版本网易云歌词无法获取

### ISSUE THREAD

**Issue by sharkysss** [jitwxs/163MusicLyrics#188]
**BUG 描述 Describe the bug**

~请在此处简要描述问题。A clear and concise description of what the bug is.~

**版本 Version**

~告知您的版本。Tell us version.~

**复现步骤 Reclaim step**

~1. xxx
2. xxx
3. xxx~

**错误日志（可选） Error Log(Optional)**

~可上传程序 `Logs` 目录下的日志文件，帮助定位问题~

**Comment by jitwxs** [comment]
请补充问题细节
