### ISSUE TITLE
建议网易和QQ音乐id自动判断

### ISSUE THREAD

**Issue by xf11075** [jitwxs/163MusicLyrics#190]
*描述您期望的功能 建议网易和QQ音乐id自动判断**

这个软件做的非常棒，想提点小建议：
因为我经常在网易云和qq音乐之间切换，下拉框选择太频繁了，网易云的id是纯数字的QQ音乐是带字母的，其实是可以按是否纯数字来自动区分是网易云的歌曲id还是QQ音乐的歌曲id，这样会更方便点，望采纳

**Comment by jitwxs** [comment]
#87 你可以直接输入整个 URL，会根据域名自动识别。现在还不会做 ID 的自动识别，因为后期加入其他来源可能会冲突。
