### ISSUE TITLE
[新功能]模糊搜索结果可以上下翻动

### ISSUE THREAD

**Issue by fgr178707** [jitwxs/163MusicLyrics#191]
页面无法上下翻动
也不可以调整窗口大小
![image](https://github.com/jitwxs/163MusicLyrics/assets/109357981/c1e548ef-b1e5-4e38-97b3-36c23bdc7f6b)

**Comment by jitwxs** [comment]
现在其实是支持翻页的，只是 QQ 音乐在未登录状态下只能范围固定条数

**Comment by fgr178707** [comment]
> 现在其实是支持翻页的，只是 QQ 音乐在未登录状态下只能范围固定条数

那能登录吗?

**Comment by jitwxs** [comment]
这块目前还不行，本软件使用的是已公开的网页接口，目前网页端即使登录也只能查询部分数据，APP 端接口目前还没有公开。
