### ISSUE TITLE
搜索一直是网络错误

### ISSUE THREAD

**Issue by kuangrenbuao** [jitwxs/163MusicLyrics#193]
**BUG 描述 Describe the bug**
17028237701367857784804732435687.jpg…]()
搜索不了，一直显示网络错误，求解决

**版本 Version**

~告知您的版本。Tell us version.~

**复现步骤 Reclaim step**

~1. xxx
2. xxx
3. xxx~

**错误日志（可选） Error Log(Optional)**

~可上传程序 `Logs` 目录下的日志文件，帮助定位问题~

**Comment by kuangrenbuao** [comment]
联网状态是这样

**Comment by TaiYouWeb** [comment]
我用也是，网易云的搜索不了，QQ倒是正常。

要是可以自定义输入网易云相关的api调用地址的话，就好了。

**Comment by jitwxs** [comment]
模糊搜索问题 #186
