### ISSUE TITLE
网易云无法获取歌词，提示网络错误，QQ音乐正常，接口可能需要更新一下

### ISSUE THREAD

**Issue by h46s15fe65656** [jitwxs/163MusicLyrics#197]
2023-12-27

**Comment by xzhzhaowendao** [comment]
我这里至今存在这个问题，希望作者关注一下。
附上故障重现视频

https://github.com/jitwxs/163MusicLyrics/assets/132211598/8ce0df5e-2a5a-4b0a-ab24-0bff6837b908

**Comment by jitwxs** [comment]
#186

**Comment by jitwxs** [comment]
[v6.1](https://github.com/jitwxs/163MusicLyrics/releases/tag/v6.1) 版本已优化该功能，感谢反馈。
