### ISSUE TITLE
添加窗口可调整大小（建议）

### ISSUE THREAD

**Issue by MNWZ211** [jitwxs/163MusicLyrics#204]
主程序显示没问题。因电脑屏幕尺寸及系统缩放设置问题，打开设置页时底部会被任务栏遮挡一部分。

**Comment by maxfun0** [comment]
设置页面无法保存，在我的电脑上看不到保存按键

**Comment by jitwxs** [comment]
https://github.com/jitwxs/163MusicLyrics/releases/tag/v6.5

**Comment by MC-dusk** [comment]
**不是报issue，只是作为记录给有需要的后来者看**
软件版本：6.5 **（暂时还没升级到7.x，7.x版本并无此问题）**
虽然已经有v7系列，v6系列到6.5就结束了，不过还是写一下：
2560x1440屏幕，100%和125%显示比例没问题，150%显示比例和更高的比例，设置页面就显示不全了，保存按钮在下面被截断导致无法保存设置。临时解决办法是改显示比例，设置完成再改回去。
相关：#178 #227
