### ISSUE TITLE
“网络错误导致响应异常”

### ISSUE THREAD

**Issue by darkzoee** [jitwxs/163MusicLyrics#205]
**BUG 描述 Describe the bug**

~请在此处简要描述问题。A clear and concise description of what the bug is.~ 正常使用时出现的程序未响应问题

**版本 Version**

~告知您的版本。Tell us version.~ **v6.0 和 v6.1 均有此问题**

**复现步骤 Reclaim step**

1.打开软件
2.复制链接并粘贴 ---> 比如https://y.qq.com/n/ryqq/songDetail/000F2wCd2BPW2I
3.选择qq音乐
4.点击精确搜索

5.然后就会卡死
6.过数分钟后显示网络错误
![image](https://github.com/jitwxs/163MusicLyrics/assets/156409276/f304769a-613f-4341-9d83-94ea54a98963)

~1. xxx
2. xxx
3. xxx~

**错误日志（可选） Error Log(Optional)**

~可上传程序 `Logs` 目录下的日志文件，帮助定位问题~

**Comment by jitwxs** [comment]
未能复现问题，请检查是否开启代理工具，或更换网络后重试
