### ISSUE TITLE
模糊搜索功能下载后无法找到文件保存位置

### ISSUE THREAD

**Issue by CorvinYu** [jitwxs/163MusicLyrics#210]
**BUG 描述 Describe the bug**

模糊搜索功能下载后无法找到文件保存位置

**版本 Version**

v6.1

**复现步骤 Reclaim step**

![image](https://github.com/jitwxs/163MusicLyrics/assets/138097462/ef5a4b0b-9213-4687-b818-3f92d11dc7ac)
![image](https://github.com/jitwxs/163MusicLyrics/assets/138097462/95dfb9f1-1081-419b-97a4-8c7e3cde1579)

点击「下载」按钮后，没有弹出任何提示，在电脑中没能找到下载的文件。
在设置中没能找到设置歌词保存位置的选项。

**Comment by jitwxs** [comment]
请阅读使用文档中关于[模糊搜索](https://github.com/jitwxs/163MusicLyrics/wiki/5.7-Plus-Guide#314-%E6%A8%A1%E7%B3%8A%E6%90%9C%E7%B4%A2)的章节，点击下载后会将歌曲信息带入主页面中并自动关闭搜索页面，后续需要在主页面手动点击保存按钮，进行下载
