### ISSUE TITLE
 目前并没有获取完整的歌词以及歌名，在大批量执行任务之后容易出现部分歌词文件命名重复的问题。

### ISSUE THREAD

**Issue by jinkelasaodang** [jitwxs/163MusicLyrics#212]
*描述您期望的功能 Describe your feature**
![截屏2024-06-28 14 33 45](https://github.com/jitwxs/163MusicLyrics/assets/84189046/a156fa96-e4d0-4bd2-a704-0be6f6527f4d)
![截屏2024-06-28 14 28 44](https://github.com/jitwxs/163MusicLyrics/assets/84189046/76e59129-8ac3-49be-af09-c56840fa9645)
![截屏2024-06-28 14 35 13](https://github.com/jitwxs/163MusicLyrics/assets/84189046/5c203151-6d25-48df-a53e-282aa82fcafc)
![截屏2024-06-28 14 35 08](https://github.com/jitwxs/163MusicLyrics/assets/84189046/e312f55c-2eec-4658-8638-379003919051)
两首歌歌名部分在原网站有的括号内容被忽略导致了文件命名重复的问题，希望能提供输出完整歌名的选项

**Comment by jitwxs** [comment]
[RELEASE from V6.3](https://github.com/jitwxs/163MusicLyrics/releases/tag/v6.3)
