### ISSUE TITLE
文档中的扫盘搜索如今失效？

### ISSUE THREAD

**Issue by Reapor-Yurnero** [jitwxs/163MusicLyrics#213]
**BUG 描述 Describe the bug**

如题 [文档中](https://github.com/jitwxs/163MusicLyrics/wiki/5.7-Plus-Guide#316-%E6%89%AB%E7%9B%98%E6%90%9C%E7%B4%A2)描述的扫盘搜索功能如今似乎在最新版本中无法使用了？

**Comment by jitwxs** [comment]
使用 v6.2 版本可正常使用，请补充复现步骤与失败信息

<img width="716" alt="20240721121608332" src="https://github.com/user-attachments/assets/31b64e27-1ef8-4472-8578-c1b3fb99f217">

**Comment by Erich1Daniel** [comment]
![Snipaste_2024-08-05_17-34-53](https://github.com/user-attachments/assets/8891dd7f-8fc9-410a-9288-8e2d1c8e2515)

**Comment by Reapor-Yurnero** [comment]
^

**Comment by maxfun0** [comment]
同样的问题

**Comment by jitwxs** [comment]
Fixed since [V6.3](https://github.com/jitwxs/163MusicLyrics/releases/tag/v6.3)，感谢反馈。
