### ISSUE TITLE
启用“QQ音乐逐字歌词”和“输出原始译文”后，输出歌词中的译文不完整。

### ISSUE THREAD

**Issue by naomoji** [jitwxs/163MusicLyrics#214]
**BUG 描述 Describe the bug**

启用“QQ音乐逐字歌词”和“输出原始译文”后，输出歌词中的译文不完整。
测试了3首歌（500907555、497988894、490490778），原文都是完整的，逐字的时间戳也都有。
但是译文只有几句，而且不是原文前几句的翻译。

**版本 Version**

v6.2

**复现步骤 Reclaim step**

1. 在“更多设置”中，勾选“QQ音乐逐字歌词”和“原始译文”
2. 回到主页，选择“QQ音乐”、“单曲”、“独立”
3. 输入歌曲ID，如“500907555”
4. 点击“精确搜索”
5. 来到歌词最后，可以看到只有几句译文，甚至没有。保存之后的结果也是一样的。结果如下图所示。
![1](https://github.com/user-attachments/assets/7925e9cf-e05e-4885-929d-24324fdcca65)
![2](https://github.com/user-attachments/assets/79dabb26-b96c-400a-8110-266a24f67f4f)
![3](https://github.com/user-attachments/assets/be595be6-c8a6-4b9c-b39e-fd25a4d32571)

**错误日志（可选） Error Log(Optional)**

无错误

**Comment by jitwxs** [comment]
Fixed since [V6.3](https://github.com/jitwxs/163MusicLyrics/releases/tag/v6.3)，感谢反馈。
