### ISSUE TITLE
建议保存文件名中多个歌手之间使用空格

### ISSUE THREAD

**Issue by maxfun0** [jitwxs/163MusicLyrics#215]
从网易云下载的歌曲，多个歌手时中间是空格，使用软件下载的歌词多个歌手之间是逗号，播放时无法匹配

**Comment by Aili1104** [comment]
这个建议增加可选项，因为下载文件名有的是空格，有的是逗号，有的是连字符，不太统一

**Comment by jitwxs** [comment]
https://github.com/jitwxs/163MusicLyrics/releases/tag/v6.5
