### ISSUE TITLE
建议增加一个命名选项

### ISSUE THREAD

**Issue by dhfhycnf** [jitwxs/163MusicLyrics#219]
希望可以增加一个音乐命名选项,避免lrc无法寻到音频文件
eg：Bad Apple!!（ 歌曲名）
        Bad Apple!! - のみこ（ 歌曲名-歌手）
        のみこ- Bad Apple!! （ 歌手-歌曲名）

**Comment by jitwxs** [comment]
可以参考 [使用文档 4.5.3 保存文件名](https://github.com/jitwxs/163MusicLyrics/wiki/5.7-Plus-Guide#453-%E4%BF%9D%E5%AD%98%E6%96%87%E4%BB%B6%E5%90%8D)
