### ISSUE TITLE
希望能增加原文和译文之间的\N分隔符识别~

### ISSUE THREAD

**Issue by HuChuYangALICE** [jitwxs/163MusicLyrics#22]
常年下外文歌哈哈，希望能有换行当分隔符把歌词分两行

**Comment by jitwxs** [comment]
使用 `优先原文` 或 `优先译文` 功能不能满足需求吗

**Comment by HuChuYangALICE** [comment]
可以是可以，就是会变成很长一行，后期视频的时候比较喜欢原文一行译文一行，不过其实先输出原文再输出译文也可以只不过我比较懒哈哈，感谢作者回复
