### ISSUE TITLE
无法扫描到本地硬盘的歌曲并下载歌曲

### ISSUE THREAD

**Issue by 1813745493** [jitwxs/163MusicLyrics#222]
![2381696bd1c80d0c0169fb63679ae204](https://github.com/user-attachments/assets/6a8f572f-1f76-4881-bbee-46fcf910865d)
![a7403668f0e5d9014c0ce1e45de8d2a2](https://github.com/user-attachments/assets/baaa0d5b-7df5-41a8-95b8-9189f4d328cd)
输入想要的硬盘地址后，显示搜索不到，在更多设置中也没有找到可以添加地址的地方。请教一下应该怎么操作

**Comment by jitwxs** [comment]
https://github.com/jitwxs/163MusicLyrics/wiki/5.7-Plus-Guide#316-%E6%89%AB%E7%9B%98%E6%90%9C%E7%B4%A2
