### ISSUE TITLE
跳过空白歌词的选项在重启应用后会被重新开启

### ISSUE THREAD

**Issue by nini22P** [jitwxs/163MusicLyrics#225]
**BUG 描述 Describe the bug**

取消了跳过空白歌词的选项并点击保存后重启应用，这个选项又会被重新开启。

**版本 Version**

v6.3

**复现步骤 Reclaim step**

1. 点击 “更多设置”
2. 取消勾选 “跳过空白行歌词”
3. 点击保存并重新打开应用
4. 点击 “更多设置”
5. 可以看到 “跳过空白行歌词” 仍是开启状态

**Comment by jitwxs** [comment]
可以开启 “设置” 里面的 “参数记忆” 功能解决，后续版本会优化下，和 “参数记忆” 功能解绑

**Comment by jitwxs** [comment]
https://github.com/jitwxs/163MusicLyrics/releases/tag/v6.5

**Comment by JINGTING0714** [comment]
为什么我的更多设置没有重置和保存选项（sos）
