### ISSUE TITLE
设置页面超出屏幕

### ISSUE THREAD

**Issue by jhsgdsfg** [jitwxs/163MusicLyrics#227]
**BUG 描述 Describe the bug**

在屏幕分辨率为1440*900的情况下，设置页面超出屏幕

**版本 Version**

v6.3

**复现步骤 Reclaim step**

1. 点击"更多设置"

**Comment by jitwxs** [comment]
https://github.com/jitwxs/163MusicLyrics/releases/tag/v6.5
