### ISSUE TITLE
歌单被识别为歌单内歌曲的第一首单曲

### ISSUE THREAD

**Issue by z0z0r4** [jitwxs/163MusicLyrics#233]
**BUG 描述 Describe the bug**

歌单 https://music.163.com/playlist?id=9589879793 会出现变成单曲的情况

![image](https://github.com/user-attachments/assets/30a172e4-fa11-4855-a3f6-04f6166b96ff)

**版本 Version**

v6.2，v6.4 则是只识别 10 首单曲

```
22811666 => 僕みたいな君 君みたいな僕 => 成功
26217602 => レインボーダー => 成功
28152563 => 砂時計 => 成功
22811662 => 恋距離遠愛 (リテイク) => 成功
22811663 => ハルイチ => 成功
22811668 => 相愛性理論 => 成功
22811660 => 三つ葉のクローバー => 成功
28152549 => 愛言葉 => 成功
410058 => 心壊サミット => 成功
22811624 => 二息歩行 => 成功

累计 10 成功 10 失败 0
```

**错误日志（可选） Error Log(Optional)**

[2024-12-29.log](https://github.com/user-attachments/files/18268892/2024-12-29.log)

**Comment by z0z0r4** [comment]
关联 https://github.com/jitwxs/163MusicLyrics/issues/224 @jitwxs 

看似将在 v6.5 修复 #224，不知道是否有效建议测试下

**Comment by jitwxs** [comment]
v6.5 版本验证没有问题

**Comment by z0z0r4** [comment]
thanks，我会在 v6.5 发布后 close

**Comment by jitwxs** [comment]
https://github.com/jitwxs/163MusicLyrics/releases/tag/v6.5
