### ISSUE TITLE
歌词文件名命名规则与网易云下载的音乐文件不同，希望能改成一样的

### ISSUE THREAD

**Issue by TristanLudrow** [jitwxs/163MusicLyrics#24]
希望能改成网易云那种 “歌手名 - 歌曲名” 的命名规则就好了

**Comment by jitwxs** [comment]
目前支持以下三种命名规则，可以自行选择的。

1. 歌曲名 - 歌手
2. 歌手 - 歌曲名
3. 歌曲名
