### ISSUE TITLE
希望增加通过多个id批量下载歌词的功能

### ISSUE THREAD

**Issue by FZDSLR** [jitwxs/163MusicLyrics#25]
一个一个点真的很累QAQ
---
PS：顺便给其他<s>被`?detail`整烦的</s>人分享一下我的经验，提取id可以直接用一个叫linkclump的浏览器插件在网易云页面上框选完成（选项选`URLS only`然后在文本编辑器里批量删除`https://music.163.com/#/song?id=`）

**Comment by jitwxs** [comment]
批量下载功能一直都支持的啊，https://www.jitwxs.cn/wiki/163-music-lyrics/3-x.html#%E5%9B%9B%E3%80%81%E6%89%B9%E9%87%8F%E6%90%9C%E7%B4%A2

**Comment by FZDSLR** [comment]
‎啊这，现在才发现readme.md导向的那个Wiki的下面还有链接，我之前还以为wiki没写完（尴尬.jpg）

发送自我的 BlackBerry 10 智能手机。
