### ISSUE TITLE
可否添加通过album id批量下载整个专辑的歌词的功能

### ISSUE THREAD

**Issue by ClydeWong** [jitwxs/163MusicLyrics#3]
例如：https://music.163.com/#/album?id=83392596

**Comment by 3066fisher** [comment]
可以从网页传输给你的一个文件里导出歌曲ID列

**Comment by 3066fisher** [comment]
可以把专辑里的所有歌都添加到一个歌单里，然后打开歌单网页（注意，是歌单，最好用火狐）按f12然后按f5刷新，找到网络（network）选项，向下滚动找到以"detail?"开头的一个json文件，单击，然后在右边窗口里点“响应”，找到"privileges"，右击，选“复制”，然后在一个支持正则的软件里（最好打开自动换行）粘贴，然后把不要的部分洗掉

> 把》},{"id":《替换为无（就是删除）
> 把》"fee":[0-9]{1,},"payed":[0-9]{1,},"st":[0-9]{1,},"pl":[0-9]{1,},"dl":[0-9]{1,},"sp":[0-9]{1,},"cp":[0-9]{1,},"subp":[0-9]{1,},"cs":[a-z]{1,},"maxbr":[0-9]{1,},"fl":[0-9]{1,},"toast":[a-z]{1,},"flag":[0-9]{1,},"preSell":[a-z]{1,}《也替换为无

然后看一下头、尾部的格式，手动删除一些不要的部分

**Comment by 3066fisher** [comment]
privilege好像只有充了VIP才会有（存疑）
但是也可以从playlist\tracks里找到
那个detail?文件里有很多信息，歌曲ID也出现了不止一次，可以好好找一找;]

**Comment by csking991225** [comment]
2021年11月15日10:48:03 detail？文件已经被删除，无法找到

**Comment by unbadfish** [comment]
@csking991225 看这里
https://github.com/unbadfish/NetEase-id-geter

**Comment by csking991225** [comment]
> @csking991225 看这里 https://github.com/unbadfish/NetEase-id-geter

感谢，但是在油猴上找到了插件支持专辑页面一键下载

**Comment by jitwxs** [comment]
v3.3 版本以添加 #35
