### ISSUE TITLE
希望能下载整个歌单的歌词

### ISSUE THREAD

**Issue by B3uzki** [jitwxs/163MusicLyrics#33]
试过使用脚本通过歌单获取歌曲id，但批量获取歌词当歌曲过多时容易失败

**Comment by jitwxs** [comment]
这块我再想想，一个是歌单变动比较频繁，另一个是在非登陆状态下，获取的歌单也不是全量的

**Comment by szlysms** [comment]
> 这块我再想想，一个是歌单变动比较频繁，另一个是在非登陆状态下，获取的歌单也不是全量的

https://greasyfork.org/zh-CN/scripts/406054-%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E6%98%BE%E7%A4%BA%E5%AE%8C%E6%95%B4%E6%AD%8C%E5%8D%95
可以参考这个油猴脚本，无登录情况下也可以查看完整歌单
