### ISSUE TITLE
更新.NET框架

### ISSUE THREAD

**Issue by textGamex** [jitwxs/163MusicLyrics#39]
希望从Framework 4.5.2更新到Framework 4.8

**Comment by jitwxs** [comment]
有什么特殊原因么？

**Comment by textGamex** [comment]
> 有什么特殊原因么？

特殊原因没有, 不过.NET Framework 4.8的性能应该更高一些

**Comment by jitwxs** [comment]
> > 有什么特殊原因么？
> 
> 因为我用的VS2022, 而VS2022不再支持.NET4.5

好的，下次更新带上

**Comment by textGamex** [comment]
> 不错，下次更新带上

谢谢

**Comment by textGamex** [comment]
@jitwxs 更新框架我现在PR行不行？

**Comment by jitwxs** [comment]
> @jitwxs 更新框架我现在PR行不行？

可以的
