### ISSUE TITLE
翻译歌词不能拿？

### ISSUE THREAD

**Issue by MilarvozM** [jitwxs/163MusicLyrics#4]
无论哪个功能试了都只有普通原文歌词，或者重复两遍

**Comment by jitwxs** [comment]
请提供歌曲ID，我会进行测试

**Comment by jitwxs** [comment]
> 无论哪个功能试了都只有普通原文歌词，或者重复两遍

请提供歌曲ID，我会进行测试

**Comment by MilarvozM** [comment]
> > 无论哪个功能试了都只有普通原文歌词，或者重复两遍
> 
> 请提供歌曲ID，我会进行测试

28892268 - 这首只会日文歌词，在选择双语的时候会重复两遍
29027453 - 这首反而只会中文翻译，选择双语也会重复
难道是中日文的区分没有做？

**Comment by jitwxs** [comment]
> > > 无论哪个功能试了都只有普通原文歌词，或者重复两遍
> > 
> > 
> > 请提供歌曲ID，我会进行测试
> 
> 28892268 - 这首只会日文歌词，在选择双语的时候会重复两遍
> 29027453 - 这首反而只会中文翻译，选择双语也会重复
> 难道是中日文的区分没有做？

试了下功能正常，你是想要什么效果？

**Comment by jitwxs** [comment]
> > > 无论哪个功能试了都只有普通原文歌词，或者重复两遍
> > 
> > 
> > 请提供歌曲ID，我会进行测试
> 
> 28892268 - 这首只会日文歌词，在选择双语的时候会重复两遍
> 29027453 - 这首反而只会中文翻译，选择双语也会重复
> 难道是中日文的区分没有做？

如果只是想要译文歌词，请先选择 `仅显示译文`，然后输入歌曲ID，最后点击`搜索`按钮即可。
