### ISSUE TITLE
搜索某些歌曲时出现 “长度不能小于0。参数名 length” 异常

### ISSUE THREAD

**Issue by hui-shao** [jitwxs/163MusicLyrics#43]
### 复现步骤

搜索歌曲id：`1413274208` 即可引发异常。复现概率100%。
搜索歌曲id: `509720124` 、`65536` 等大部分歌曲无异常。

### 补充说明
操作系统：Windows 10 21H2 19044.1586

测试了 v3.4 ~ v3.6 均有异常

### 问题截图

![2022-03-19_130218](https://user-images.githubusercontent.com/31568606/159107865-a3e792bf-5b8c-494a-9487-53b53e33c592.png)

**Comment by jitwxs** [comment]
v3.7 已修复
