### ISSUE TITLE
加个批量输入分享链接自动提取ID

### ISSUE THREAD

**Issue by DoctorKoKoDaYo** [jitwxs/163MusicLyrics#48]
直接复制分享链接然后自动识别出ID，免得要从客户端复制然后再手动选择看
（我是懒狗）

**Comment by DoctorKoKoDaYo** [comment]
就是开个窗口然后可以把复制的歌曲分享链接粘贴进去，自动提取出歌曲ID

**Comment by jitwxs** [comment]
输入框可以增加链接自动提取ID的功能，下个版本中增加吧
