### ISSUE TITLE
添加更多平台的歌词获取来源

### ISSUE THREAD

**Issue by daoxi** [jitwxs/163MusicLyrics#49]
在另个[名叫LyricCapture的repo](https://github.com/ElliottSilence/LyricCapture)发现了很相似的歌词获取软件，其同时支持QQ音乐和网易云，这个软件也是用C#写的，但自从发布后就没再更新过了。

QQ音乐目前的版权比网易云多不少所以能下到的歌词也更多，其歌词格式也更统一。不知作者有没有兴趣根据这人的源码来添加获取QQ音乐歌词与翻译的功能？或者fork这个repo后进行维护更新？

**Comment by jitwxs** [comment]
可以的，有空我添加下

**Comment by jitwxs** [comment]
#72
