### ISSUE TITLE
提问: 作者为什么不用WPF开发呢, winform已经是很老的技术了

### ISSUE THREAD

**Issue by textGamex** [jitwxs/163MusicLyrics#65]

**Comment by jitwxs** [comment]
一个原因是这个是17年的项目，当时限于自身技术使用了winform。第二个原因是后面主做 Java 开发，c# 这边技术没啥长进，hhh

**Comment by textGamex** [comment]
> 一个原因是这个是17年的项目，当时限于自身技术使用了winform。第二个原因是后面主做 Java 开发，c# 这边技术没啥长进，hhh

只能说很真实了233
