### ISSUE TITLE
空行可能会显示分隔符

### ISSUE THREAD

**Issue by 3066fisher** [jitwxs/163MusicLyrics#7]
外文歌曲如果选择合并，批量保存可能会出现方括号后面带分隔符的情况如

> [00:23.56]歌词
> [00:26.32]#<----应该是空白行
> [00:27.76]歌词
> 或者
> [by:小您同学]#<----应该没有井号

（我又来了）【划掉】祝楼主生活顺利

**Comment by jitwxs** [comment]
请提供下出现该问题的歌曲ID

**Comment by 3066fisher** [comment]
你好，太晚了，明天再发，约9:25左右
谢谢





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jitwxs"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月1日(星期三) 晚上11:18
收件人:&nbsp;"jitwxs/163MusicLyrics"<163MusicLyrics@noreply.github.com&gt;;
抄送:&nbsp;"泪过无痕"<3066893506@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jitwxs/163MusicLyrics] 空行可能会显示分隔符 (#7)





 
请提供下出现该问题的歌曲ID

**Comment by 3066fisher** [comment]
使用如下id串

> 532776373,532940302,532940303,532777386,532776374,532777387,532776375,532940304,532777388,532940305,532776376,532776377,532950272,532777389

**Comment by 3066fisher** [comment]
![newUI](https://user-images.githubusercontent.com/61961263/78209837-c11fca00-74da-11ea-8f2e-bef9cf616371.png)
画了一个新UI
qt不知道为什么装不上去，不然就会给一个.ui文件了
就在这里发图片吧

**Comment by jitwxs** [comment]
分隔符这个问题我会尽快修复。关于新UI的建议，暂时不会考虑对功能本身无关的调整，感谢你的建议。

**Comment by jitwxs** [comment]
问题已修复

**Comment by 3066fisher** [comment]
你好，请问一下能发布在网页上找数据时使用的headers吗
我在家看代码，电脑内存4个G，伤不起啊



---原始邮件---
发件人: "jitwxs"<notifications@github.com&gt;
发送时间: 2020年4月1日(周三) 晚上11:18
收件人: "jitwxs/163MusicLyrics"<163MusicLyrics@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"3066fisher"<3066893506@qq.com&gt;;
主题: Re: [jitwxs/163MusicLyrics] 空行可能会显示分隔符 (#7)




 
请提供下出现该问题的歌曲ID

**Comment by jitwxs** [comment]
> 你好，请问一下能发布在网页上找数据时使用的headers吗 我在家看代码，电脑内存4个G，伤不起啊
> […](#)
> ---原始邮件--- 发件人: "jitwxs"<notifications@github.com&gt; 发送时间: 2020年4月1日(周三) 晚上11:18 收件人: "jitwxs/163MusicLyrics"<163MusicLyrics@noreply.github.com&gt;; 抄送: "Author"<author@noreply.github.com&gt;;"3066fisher"<3066893506@qq.com&gt;; 主题: Re: [jitwxs/163MusicLyrics] 空行可能会显示分隔符 (#7) 请提供下出现该问题的歌曲ID — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我使用的是网易云的老版本API，不需要headers的方式。https://github.com/jitwxs/163MusicLyrics/blob/e013b18063fd8579db783138905142e0db36bcef/WindowsFormsApp1/Form1.cs#L20
