### ISSUE TITLE
按专辑下载时遇到没有歌词的歌曲会生成0kb的空lrc文件

### ISSUE THREAD

**Issue by 2fdvr** [jitwxs/163MusicLyrics#74]
**BUG 描述 Describe the bug**

~请在此处简要描述问题。A clear and concise description of what the bug is.~
按专辑下载时遇到没有歌词的歌曲会生成0kb的空lrc文件
**版本 Version**
v4.0
~告知您的版本。Tell us version.~

**复现步骤 Reclaim step**

1. 例如https://music.163.com/#/album?id=87958032 中的这首歌 https://music.163.com/#/song?id=1440360417
2. xxx
3. xxx~

**Comment by jitwxs** [comment]
已复现，下个版本会修复它
