### ISSUE TITLE
添加保存默认选项的功能 Adding the feature to save default options

### ISSUE THREAD

**Issue by daoxi** [jitwxs/163MusicLyrics#76]
如题，目前每次打开都要重新选择各种设置（比如选择哪个平台，如何显示译文，是否强制两位，等等），建议能够保存这些选项，下次打开时就不用再麻烦了。

比如可以把这些设置存储于同目录的一个.ini文件中（首次打开程序后生成），这样以后下载新版覆盖安装时也会保留设置（因为配置文件不包含于绿色版程序包中）。

顺带一提，Github提建议时英文提示的“Please input hear”应该打错了是“here”吧。

**Comment by jitwxs** [comment]
好的，下个版本中添加
