### ISSUE TITLE
搜索报错

### ISSUE THREAD

**Issue by Chenx221** [jitwxs/163MusicLyrics#8]
歌曲ID：28151022、1428179190
搜索失败，错误信息：
startIndex cannot be larger than length of string.
Parameter name: startIndex

**Comment by jitwxs** [comment]
抱歉，问题未复现

**Comment by Chenx221** [comment]
设置成“不显示译文”不会报错
但设置成“合并显示，优先原文”会报错

**Comment by jitwxs** [comment]
感谢反馈，v2.8 已修复
