### ISSUE TITLE
Issues with HTML/XML Escape Characters

### ISSUE THREAD

**Issue by daoxi** [jitwxs/163MusicLyrics#80]
When trying to download certain lyrics that contain escaped characters, the characters are not converted into their original forms.

To reproduce the bug:

For example, for QQ Music ID: 001HeMEN0hplNv

part of the downloaded lyrics contains
**We\&apos;re**
instead of
**We're**
(the "\&apos;" part is not converted to an actual apostrophe: ' )

it also contains
**\&quot;hell yeah\&quot;**
instead of
**"hell yeah"**
(the "\&quot;" part is not converted to a double quotation mark: " )

Version tested: v4.0

**Comment by jitwxs** [comment]
got it, it will be fixed in next version
