### ISSUE TITLE
优先原文(独立)和优先原文(独立)模式导出srt时间错误

### ISSUE THREAD

**Issue by djj45** [jitwxs/163MusicLyrics#86]
<img src="https://user-images.githubusercontent.com/84726879/166408854-c63d1c1a-4030-4ce4-9c72-dde55c792ddf.png" width=500>

优先原文（独立）和优先原文（交错）模式导出srt，中文与外文交界的那一句歌词时间错误

**Comment by jitwxs** [comment]
`优先原文（独立）`和`优先译文（独立）`这两个模式，是不支持导出 SRT 的，不然没法处理交界的时间

**Comment by djj45** [comment]
> `优先原文（独立）`和`优先译文（独立）`这两个模式，是不支持导出 SRT 的，不然没法处理交界的时间

为什么不能处理交界的时间，最后一句持续时间默认6秒，跟普通的srt一样不行吗

**Comment by jitwxs** [comment]
> > `优先原文（独立）`和`优先译文（独立）`这两个模式，是不支持导出 SRT 的，不然没法处理交界的时间
> 
> 为什么不能处理交界的时间，最后一句持续时间默认6秒，跟普通的srt一样不行吗

这个可以
