### ISSUE TITLE
去掉qq音乐和网易云音乐的选项

### ISSUE THREAD

**Issue by djj45** [jitwxs/163MusicLyrics#87]
qq音乐的id是字母加数字，网易云音乐的id是纯数字，建议去掉选项，自动判断来源

**Comment by jitwxs** [comment]
可以增加一个自动识别的选项，这两个来源还是保留着吧，预留后面的其他来源

**Comment by jitwxs** [comment]
[v5.6](https://github.com/jitwxs/163MusicLyrics/releases/tag/v5.6) 版本支持了自动识别，如果输入的是完整的网址，会根据网址的内容，自动识别音乐提供商、搜索类型。
