### ISSUE TITLE
希望能新增批量讀取文件夾內的ID

### ISSUE THREAD

**Issue by burstmasker** [jitwxs/163MusicLyrics#93]
*描述您期望的功能 Describe your feature**因為下載歌曲時自帶了歌詞文件，希望可以加入讀取文件夾的功能，當前資料夾內有700多首音樂，一個一個ID輸入的話是個大工程...辛苦了

**Comment by jitwxs** [comment]
可以提供下文件夹内文件名称列表的截图吗，看好不好实现

**Comment by burstmasker** [comment]
謝謝大佬，辛苦了!

**Comment by jitwxs** [comment]
详见 https://github.com/jitwxs/163MusicLyrics/wiki/4.x-Guide 中 `扫盘搜索` 功能
