### ISSUE TITLE
4.2依赖问题

### ISSUE THREAD

**Issue by llq520** [jitwxs/163MusicLyrics#94]
更多设置内-译文显示罗马音勾选提示需要lpadic，在代码仓库没有找到.哪里可以下载？

**Comment by jitwxs** [comment]
https://github.com/jitwxs/163MusicLyrics/wiki/4.x-Guide 第一小节

**Comment by llq520** [comment]
双语歌词生成SRT有bug 第一文对应时间轴正常 第二文会顺序排到最后
例如一首歌3分钟 50行歌词  原文编号为1-50  译文编号为51-100  实际上第51句字幕时候歌曲已经播放完了。

**Comment by llq520** [comment]
我截取了一部分做说明 

1
00:00:00,000 --> 00:00:03,043
 作曲 : Nao

2
00:00:00,000 --> 00:00:03,043
ヾ(╹◡╹)ﾉﾞ

3
00:00:03,043 --> 00:00:07,015
今好きな人はいますか？

4
00:00:07,015 --> 00:00:09,082
今気になる人はいますか？

5
00:00:09,082 --> 00:00:15,060
どんなタイプの人が好きですか？

对应译文

74
00:00:00,000 --> 00:00:03,043
ヾ(╹◡╹)ﾉﾞ

75
00:00:03,043 --> 00:00:07,015
现在有喜欢的人吗？

76
00:00:07,015 --> 00:00:09,082
现在有在意的人吗？

77
00:00:09,082 --> 00:00:15,060
你喜欢什么类型的人呢？

78
00:00:15,060 --> 00:00:18,031
有人给你发邮件吗？

**Comment by llq520** [comment]
这是我用excel vba调整后的

00:00:00,000 --> 00:00:03,043
ヾ(╹◡╹)ﾉﾞ作曲 : Nao
ヾ(╹◡╹)ﾉﾞ作曲 : Nao
 
00:00:03,043 --> 00:00:07,015
今好きな人はいますか？
现在有喜欢的人吗？
 
00:00:07,015 --> 00:00:09,082
今気になる人はいますか？
现在有在意的人吗？
 
00:00:09,082 --> 00:00:15,060
どんなタイプの人が好きですか？
你喜欢什么类型的人呢？
 
00:00:15,060 --> 00:00:18,031
メールしてる人はいますか？
有人给你发邮件吗？

**Comment by djj45** [comment]
> 双语歌词生成SRT有bug 第一文对应时间轴正常 第二文会顺序排到最后 例如一首歌3分钟 50行歌词 原文编号为1-50 译文编号为51-100 实际上第51句字幕时候歌曲已经播放完了。

换个播放器吧，potplayer可以正常播放，或者用aegisub转换成ass格式再播放
