### ISSUE TITLE
最後一行歌詞會不見

### ISSUE THREAD

**Issue by haruma1115** [jitwxs/163MusicLyrics#95]
**BUG 描述 Describe the bug**

~请在此处简要描述问题。A clear and concise description of what the bug is.~

**版本 Version**
4.3
~告知您的版本。Tell us version.~

**复现步骤 Reclaim step**

直接搜尋時(網易雲音樂)，會發現歌詞會址少一行

**错误日志（可选） Error Log(Optional)**

~可上传程序 `Logs` 目录下的日志文件，帮助定位问题~

**Comment by haruma1115** [comment]
[[](url)](https://i.imgur.com/tMMX9wk.png)
如這張附圖，再麻煩您了 謝謝

**Comment by jitwxs** [comment]
已复现，下一版本会修复
