### ISSUE TITLE
能否加入歌詞時間的格式更改功能?

### ISSUE THREAD

**Issue by burstmasker** [jitwxs/163MusicLyrics#99]
因walkman只識別這樣的格式
![image](https://user-images.githubusercontent.com/105626897/170827767-ab99e32b-f8e0-431b-b9f3-73cbb68229f3.png)
而我們導出的格式為
![image](https://user-images.githubusercontent.com/105626897/170827788-78a20063-9b35-474c-a64e-3dd3f94244c3.png)

[00:00.000]不知道這個時間中的.能否統一改為:或是直接捨去?麻煩大大了!

**Comment by jitwxs** [comment]
可以的，下一版本中添加

**Comment by jitwxs** [comment]
https://github.com/jitwxs/163MusicLyrics/wiki/4.x-Guide#421-%E6%97%B6%E9%97%B4%E6%88%B3%E6%A0%BC%E5%BC%8F
